server {
    listen 8080; 
    server_name 221.121.4.48; 

    root /var/www/devops-hackathon-de02/pthung-k24cntt2/src; 
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
